### ISSUE TITLE
Attributes on html tag

### ISSUE THREAD

**Issue by milelo** [ibdknox/crate#17]
Is it possible to attach attributes to the html tag eg "<html manifest="app.manifest">". Awesome software, thanks!

**Comment by ibdknox** [comment]
yep!

``` clojure
[:a {:href "cool" :some-attribute "blah"} "content"]
```

Edit: ah.. do you mean on the root <html> tag?

**Comment by milelo** [comment]
Yes, I need to add the attributes to the "html" tag itself:

This attribute doesn't do anything:

(html5 {:manifest "app.manifest"}
  [:head

This leads to additional nested html tags.

(html5 
   [:html {:manifest "app.manifest"}
    [:head

Thanks.

**Comment by ibdknox** [comment]
did you mean hiccup? Crate is for Clojurescript, which by the time that would run would already have an html tag in place :)

https://github.com/weavejester/hiccup/

**Comment by milelo** [comment]
Hi Chris,
  I'm using Crate with clojurescript, I understand that it already has a html tag, the problem I have is I need to add attributes to the <html> tag itself but as this is implicit I couldn't find a way to do this, if I add a map with the attributes after  "(html5" it isn't included in the generated <html> tag. Thanks, Mike

**Comment by milelo** [comment]
Sorry, stupid me, yes I'm referring to hiccup; I'm using Crate most of the time with ClojureScript and got mixing up where I was. Thanks again Mike

**Comment by clojens** [comment]
There would be cases where there may be a dom ready and operating within, yet at the same time not the target our crate operations are pointed at. For example, my use-case writing asciidoctor plugin for LT, I had some issues with rendering in panel and wanted to write out a file using simple hiccup/crate html forms to `.innerHTML` raw string (which means I can just always prefix the doctype root element so its no biggie, but I thought I'd share that I do think there are viable causes for this feature and which is reason why hiccup does actually include it - not that this should be an argument, just saying :)

I don't know...maybe my 'demands' are just quirky though. I also wanted to experiment and try to parse the rendered asciidoc output html back to a AST/parsed using some node.js libs, finally resorting to copying a few hickory cljs parts and enabling it for myself in this case. I recon crate suffices for 95% of the use-cases anyone currently has scaffolding UI elements in LT (and assuming that matters to begin with, no idea where else crate is used and how stable the API is, as 2013 was the last update and if much relies on its use, I imagine patching the missing features yourself or via plugin is the preferred route of least impact)
