### ISSUE TITLE
createElementNS unsupported in IE 8 and less

### ISSUE THREAD

**Issue by wilkes** [ibdknox/crate#2]
https://github.com/ibdknox/crate/blob/master/src/crate/core.cljs#L76

I worked around it with this:

https://github.com/wilkes/crate/commit/a547b2f230720ad42a53958da19693af6628f6af

This patch silently ignores namespaces in IE8, not sure what the desired behavior should be.  If you this meets your needs I'll open pull request.  Another alternative is to just use `createElement`.  Not sure what the goals for crate.

**Comment by ibdknox** [comment]
Fixed in alpha3
