### ISSUE TITLE
[:svg ...] converted to dom is not visible.

### ISSUE THREAD

**Issue by soulne4ny** [ibdknox/crate#20]
The statement `(dom/append (dom/getElement "test") (crate/html drawing))` changes the DOM node `test` as expected, but visually nothing changes.  However, in Opera produced node tags are in uppercase, like `<SVG ...>`.

Setting `innerHTML` like

```
(set! (.-innerHTML (dom/getElement "test")) (dom/getOuterHtml (crate/html drawing)))
```

has visual effect and produces same DOM nodes.

Tested in FF, Chrome, Opera.

```
(ns test
    (:require
        [goog.dom :as dom]
        [crate.core :as crate]))

(def drawing [:svg
        {:style "display:block;margin:auto;height:100;width:100;background-color:#222222"}
        [:rect {
            :style "fill:orange"
            :x 10 :y 10
            :height 80 :width 80
        }]])
```

**Comment by ibdknox** [comment]
you have to prefix svg tags with their namespace: 

``` clojure
[:svg:svg ... ]
```

**Comment by soulne4ny** [comment]
Yes, it works :)
Thanks a lot for the library!
