### ISSUE TITLE
Inserting crate-generated element via jquery is puzzling

### ISSUE THREAD

**Issue by tobyhede** [ibdknox/crate#3]
Run into a rather interesting problem.

An element generated as html and inserted into the page via jquery does not pick up the assigned styles. 

The style is in the HTML, but the browser (Chrome, Firefox) does not render it at all. 

The generated html can be saved via the browser, and the HTML file when opened DOES have the style applied.

The same code generated via javascript directly (bypassing crate) or by using an explicit html string from within clojurescript also has the correct style.

It appears to be an issue with crate-generated elements only. 

eg:

```
(-> (jquery "body")         
  (.append (crate/html [:h1{:class "red"} "Test inside a jquery"]) ))))
```

Where the red class simply defines:

```
.red {
color:red;
}
```

I have tried several variations of crate here including defpartial, defhtml with the same results. 
Same results using jayq or non-wrapped jquery. 
Similarly, using different jquery methods (inner, append, html, etc).

Am I missing something very obvious?

**Comment by ibdknox** [comment]
hm what version of crate?

I tested the following in chrome and ff and it worked:

``` Clojure
(append $body (crate/html [:p {:class "error"} "oh nos"]))
(append $body (crate/html [:p.error "oh nos"]))
```

``` css
.error { color: red; }
```

whoops, didn't mean to close it.

**Comment by tobyhede** [comment]
running off master, have the changes that removed the group id

**Comment by tobyhede** [comment]
Also, your code is using jayq? And setting $body up with def?

**Comment by tobyhede** [comment]
Same deal. Curious.

**Comment by tobyhede** [comment]
OK, got it working. I may have hit a bug in clojurescript itself ... if I remove one of my functions, the style suddenly is applied correctly. 

Thanks for your help & letting me talk to the duck http://www.codinghorror.com/blog/2012/03/rubber-duck-problem-solving.html

**Comment by ibdknox** [comment]
if you can get a simple repro of it, I'd be happy to take a look.

In either case, glad it started working :)

**Comment by tobyhede** [comment]
I had a function called "get" in my codebase, removing or renaming this function and everything started working as advertised:

```
(defn get [])
```

Not 100% sure what this was actually conflicting with, as the only other instances of "get" in the system are all namespaced to other JS objects (sone in the google closure stuff and one in clojurescript core).

**Comment by ibdknox** [comment]
It was conflicting with clojure.core/get. If you replace the name of a clojure.core function, make sure you do 

``` clojure
(ns my-awesome-ns
  (:refer-clojure :exclude [get]))
```

ClojureScript doesn't currently fail gracefully there.

**Comment by tobyhede** [comment]
Ah ... but isn't all this stuff namespaced? 

In the generated js it comes through as:

```
clojure.core.get
my.app.get
```

Regardless, the side-effect of breaking CSS  is very strange. 

Anyway, thanks. Crate rocks, btw!
